Repository gdgoc-konkuk/landing-page, pull requests merged in 2024-07, with the labels that each got.

#2 Initial setup and header & footer implementation
  .github/PULL_REQUEST_TEMPLATE.md
  app/_component/Footer.tsx
  app/_component/Header.tsx
  app/favicon.ico
  app/globals.css
  app/layout.tsx
  app/page.tsx
  public/fonts/GoogleSans-Bold.ttf
  public/fonts/GoogleSans-Medium.ttf
  public/fonts/GoogleSans-Regular.ttf
  public/fonts/PretendardVariable.woff2
  public/fonts/SUITEVariable.woff2
  public/images/footer/github.svg
  public/images/footer/instagram.svg
  public/images/header/header-symbol.png
  tailwind.config.ts
Labels: documentation, enhancement

#3 Main section Implementation
  app/_component/Header.tsx
  app/_component/main/Logo.tsx
  app/_component/main/Main.tsx
  app/page.tsx
  components/ui/ApplyButton.tsx
  tailwind.config.ts
Labels: enhancement

#4 Develop to Main
  .github/PULL_REQUEST_TEMPLATE.md
  app/_component/Footer.tsx
  app/_component/Header.tsx
  app/_component/main/Logo.tsx
  app/_component/main/Main.tsx
  app/favicon.ico
  app/globals.css
  app/layout.tsx
  app/page.tsx
  components/ui/ApplyButton.tsx
  public/fonts/GoogleSans-Bold.ttf
  public/fonts/GoogleSans-Medium.ttf
  public/fonts/GoogleSans-Regular.ttf
  public/fonts/PretendardVariable.woff2
  public/fonts/SUITEVariable.woff2
  public/images/footer/github.svg
  public/images/footer/instagram.svg
  public/images/header/header-symbol.png
  tailwind.config.ts
Labels: enhancement

#5 Solution Challenge section Implementation
  app/_component/solution-challenge/SolutionCard.tsx
  app/_component/solution-challenge/SolutionChallenge.tsx
  app/layout.tsx
  app/page.tsx
  package.json
  public/fonts/GangwonEduPower.woff2
  public/images/solution/glowalarm.png
  public/images/solution/pathpal.png
  tailwind.config.ts
  yarn.lock
Labels: enhancement

#7 Review section Implementation
  app/_component/review/Review.tsx
  app/_component/review/SlidingCard.tsx
  app/page.tsx
  components/ui/card.tsx
  components/ui/carousel.tsx
  package.json
  public/images/review/reviewCardBuildwithAI.png
  public/images/review/reviewCardDanggn.png
  public/images/review/reviewCardFlutter.png
  public/images/review/reviewCardGDSCGermany.png
  public/images/review/reviewCardGraduation.png
  public/images/review/reviewCardHanyang.png
  public/images/review/reviewCardKprintf.png
  public/images/review/reviewCardMTandTrip.png
  public/images/review/reviewCardRegularSeminar.png
  public/images/review/reviewCardWRTN.png
  public/next.svg
  public/vercel.svg
  yarn.lock
Labels: enhancement, help wanted
